### PR TITLE
Blog in documentation website

### LINKED ISSUE #253: [Docs]: Blog in documentation website
## How can the documentation be improved?

Can be used for discussions on specific features, highlight a plugin, or to post change notes

### PR DESCRIPTION
**Pull request by AryanAb**
## Summary of Changes

Adds a blog section to the project website. The blog page is paginated with 5 posts appearing per page. The blog posts are written in Markdown with frontmatter metadata defined at the top of each file (`+++` for TOML and `---` for YAML).

A first blog post is included in the PR. Screenshots are included below:

shrs4
shrs5

## Implementation Details

The templates are changed very slightly. Thus, the AdiDoks directory is no longer a sub-module and contains the appropriate files.

Closes #253

### CODE REVIEW

**Comment by AryanAb** [comment]
It would be great if someone could pull the changes and serve the Zola website to verify if the blog works properly.

**Comment by nithinmuthukumar** [comment]
It makes sense that we should maintain our own version of the theme so that we can make changes to it. Might be a better idea to fork adidoks under the shrs org and continue to use it as a submodule. The blog itself looks great!

**Comment by MrPicklePinosaur** [comment]
> It makes sense that we should maintain our own version of the theme so that we can make changes to it. Might be a better idea to fork adidoks under the shrs org and continue to use it as a submodule. The blog seems to work properly and looks great!

Yeah thats a good idea, lets fork the theme and keep it a submodule.  @AryanAb we have a WIP organization for shrs and I can invite you to that.

**Comment by AryanAb** [comment]
The code in the PR is now using the forked repo in the organization. Feel free to change the contents of the blog post as you see fit.

**Pull request merged**
